apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-worker-6663
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/auth-worker-6663
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
